version: 0.2

env:
  variables:
    DOCKER_IMAGE: 'my-docker-image'
    DOCKER_REGISTRY: 'albert1w22/awsrepodocker'
    SONAR_HOST_URL: 'http://200.118.80.164:9000' # Dirección pública del servidor SonarQube
    SONAR_TOKEN: 'sqp_fe0bd42c0771f7fdcb4cb8584f546f37a5d0dac0'

phases:
  install:
    commands:
      - echo "Instalando Java y Gradle..."
      - apt-get update
      - apt-get install openjdk-17-jdk -y
      - apt-get install gradle -y
      - java -version

  pre_build:
    commands:
      - echo "Moviéndome al subdirectorio gitaws..."
      - cd gitaws
      - echo "Estableciendo permisos para gradlew..."
      - chmod +x gradlew
      - ls -la

  build:
    commands:
      - echo "Iniciando análisis con SonarQube..."
      - cd gitaws # Cambiar al subdirectorio nuevamente si es necesario
      - ./gradlew clean test jacocoTestReport sonarqube \
        -Dsonar.host.url=$SONAR_HOST_URL \
        -Dsonar.login=$SONAR_TOKEN
      - echo "Análisis con SonarQube completado."

  post_build:
    commands:
      - echo "Moviéndome al subdirectorio gitaws..."
      - cd gitaws
      - echo "Construyendo y subiendo imagen de Docker..."
      - docker build -t $DOCKER_REGISTRY/$DOCKER_IMAGE .
      - docker push $DOCKER_REGISTRY/$DOCKER_IMAGE
      - echo "Imagen de Docker subida al repositorio."

artifacts:
  files:
    - gitaws/build/libs/*.jar # Ajusta la ruta para los artefactos, según la estructura de tu proyecto
  discard-paths: no
