version: 0.2

env:
  variables:
    DOCKER_IMAGE: 'my-docker-image'
    DOCKER_REGISTRY: 'albert1w22/awsrepodocker'
    JAVA_HOME: 'C:\\Program Files\\Java\\jdk-17'
    GRADLE_HOME: 'C:\\Gradle'

phases:
  install:
    commands:
      - echo "Instalando Java y Gradle..."
      - apt-get install openjdk-17-jdk -y
      - apt-get install gradle -y
      - java -version

  pre_build:
    commands:
      - echo "Estableciendo permisos para gradlew..."
      - chmod +x gradlew
      - ls -la gradlew

  build:
    commands:
      - echo "Iniciando compilación y pruebas con Gradle..."
      - ./gradlew clean test jacocoTestReport sonarqube --stacktrace --info
      - echo "Compilación y análisis completados."

  post_build:
    commands:
      - echo "Construyendo y subiendo imagen de Docker..."
      - docker build -t $DOCKER_REGISTRY/$DOCKER_IMAGE .
      - docker push $DOCKER_REGISTRY/$DOCKER_IMAGE
      - echo "Imagen de Docker subida al repositorio."

artifacts:
  files:
    - target/*.jar
  discard-paths: no
